### ISSUE TITLE
Failed to stop cleanly

### ISSUE THREAD

**Issue by templatedop** [Trendyol/chaki#21]
Hi,

I just ran server examples .
For example ran "server" in  "examples" folder
Everything works fine but when stop server following error is shown

`[Fx] ERROR              Failed to stop cleanly: sync /dev/stderr: The handle is invalid.
exit status 1`

Request to kindly help on this

**Comment by ahmetcanozcan** [comment]
Hi, I've just checked, and it looks like everything is fine. Would you share more detailed information about your environment and the command used to run the example?

**Comment by templatedop** [comment]
Hi
OS is windows 11 pro
Ran command "go run ."  in VS code
Screen shot attached.


<img width="563" alt="failed to stop cleanly" src="https://github.com/user-attachments/assets/3c729e5e-ad66-4744-9d43-5278ea9d37cf">

**Comment by ahmetcanozcan** [comment]
Thanks for the response, I'll check more detailed this issue.

**Comment by templatedop** [comment]
I would like to implement chaki in my organisation
Request your support.
I have contacted you ....

**Comment by ispiroglu** [comment]
Hi @templatedop, it appears to be an error from [zap](https://github.com/uber-go/zap) itself.
As I inspect, there are no solutions for that and it has a low priority in zap's backlog.

I don't see any bad side-affects about ignoring the error but if you do, feel free to report it. 

There are two issues linked in the PR, you can checkout them also.

**Comment by templatedop** [comment]
Thank you
