### ISSUE TITLE
ErrHandler should be provided Module option instead of app.Provide

### ISSUE THREAD

**Issue by ahmetcanozcan** [Trendyol/chaki#23]

**Comment by ispiroglu** [comment]
### Desc
Currently, Chaki requires an error handler to convert errors to a response. It already has a default error handler but it is required to being provided to application. 

```go

	app.Provide(
		middlewares.ErrHandler, // <-
                // ...
	)
```

With this task, this errHandler should be provided to the application if non custom provided.
