### ISSUE TITLE
Get http resources where input not expected

### ISSUE THREAD

**Issue by templatedop** [Trendyol/chaki#32]
Hi,
How to deal with with Get http resources where input is not expected

Chaki expects to have some input. But how to deal with cases where there is no input necessary especially Gets.

Kindly guide.

**Comment by ahmetcanozcan** [comment]
Hi you can ignore the input case  with a function like this
 ```golang
func (ct *fooController) getNoReq(ctx context.Context, _ any) (string, error) {
  return "ok", nil
}
```
you can do the same thing for response as well
```golang
func (ct *fooController) getNoReqAndNoResponse(ctx context.Context, _ any) (any, error) {
  return  nil, nil
}
```
